export const clientConstants = {
 ADD_CLIENT : 'ADD_CLIENT',
 ADD_CLIENT_SUCCESS: 'ADD_CLIENT_SUCCESS',
 ADD_CLIENT_FAILURE: 'ADD_CLIENT_FAILURE',
//List(Read)
 LIST_CLIENTS_SUCCESS: 'LIST_CLIENTS_SUCCESS',
 LIST_CLIENTS_FAILURE: 'LIST_CLIENTS_FAILURE',
//Delete
 DELETE_CLIENT_SUCCESS: 'DELETE_CLIENT_SUCCESS',
 DELETE_CLIENT_FAILURE: 'DELETE_CLIENT_FAILURE',
//Ver(Read)
 ONLY_CLIENT: 'ONLY_CLIENT',
//Register/Login
 LOGIN :"LOGIN",
 LOGOUT :"LOGOUT",
 CREATE_LOGIN_USER:"CREATE_LOGIN_USER",
}



