//Constants OF Employe
//Add(Create)
export const ADD_EMPLOYE = 'ADD_EMPLOYE';
export const ADD_EMPLOYE_SUCCESS = 'ADD_EMPLOYE_SUCCESS';
export const ADD_EMPLOYE_FAILURE = 'ADD_EMPLOYE_FAILURE';

//List(Read)
export const LIST_EMPLOYES = 'LIST_EMPLOYES';
export const LIST_EMPLOYES_SUCCESS = 'LIST_EMPLOYES_SUCCESS';
export const LIST_EMPLOYES_FAILURE = 'LIST_EMPLOYES_FAILURE';

//Delete
export const DELETE_EMPLOYE = 'DELETE_EMPLOYE';
export const DELETE_EMPLOYE_SUCCESS = 'DELETE_EMPLOYE_SUCCESS';
export const DELETE_EMPLOYE_FAILURE = 'DELETE_EMPLOYE_FAILURE';

//Ver(Read)
export const ONLY_EMPLOYE = 'ONLY_EMPLOYE';


//Edit
export const EDIT_EMPLOYE = 'EDIT_EMPLOYE';
