//Constants OF Employe
//Add
export const ADD_EMPLOYE = 'ADD_EMPLOYE';
export const ADD_EMPLOYE_SUCCESS = 'ADD_EMPLOYE_SUCCESS';
export const ADD_EMPLOYE_FAILURE = 'ADD_EMPLOYE_FAILURE';

//List
export const LIST_EMPLOYES = 'LIST_EMPLOYES';
export const LIST_EMPLOYES_SUCCESS = 'LIST_EMPLOYES_SUCCESS';
export const LIST_EMPLOYES_FAILURE = 'LIST_EMPLOYES_FAILURE';

