export const orderConstants = {
    //(Orden)
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE:'ADD_ORDER_FAILURE',
    //List
    LIST_ORDER_CITAS_SUCCESS:'LIST_ORDER_CITAS',
    LIST_ORDER_CITAS_FAILURE:'LIST_ORDER_CITAS_FAILURE',
    //Delete
    DELETE_CITA:'DELETE_CITA_SUCCESS',
    DELETE_CITA_FAILURE:'DELETE_CITA_FAILURE',
    //(Citas)
    ADD_CITAS_SUCCESS: 'ADD_CITAS_SUCCESS',
    ADD_CITAS_FAILURE:'ADD_CITAS_FAILURE',
    //(Cliente)
    LIST_ORDER_CLIENT_SUCCESS: 'LIST_ORDER_CLIENT_SUCCESS',
    LIST_ORDER_CLIENT_FAILURE:'LIST_ORDER_CLIENT_FAILURE',
    //Carrito
    ADD_CARRITO: 'ADD_CARRITO'
}  
   