export const serviceConstants = {
 ADD_SERVICE : 'ADD_SERVICE',
 ADD_SERVICE_SUCCESS: 'ADD_SERVICE_SUCCESS',
 ADD_SERVICE_FAILURE: 'ADD_SERVICE_FAILURE',
//List(Read)
 LIST_SERVICES_SUCCESS: 'LIST_SERVICES_SUCCESS',
 LIST_SERVICES_FAILURE: 'LIST_SERVICES_FAILURE',
//Delete
 DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
 DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',
//Ver(Read)
 ONLY_SERVICE: 'ONLY_CLIENT',
//Edit
EDIT_SERVICE:'EDIT_SERVICE'
}